services:
  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 30s
      retries: 3

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./web-app:/app
      - ./web-app/logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
